# Generated by Django 6.0.1 on 2026-01-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Nomi (Uzbek)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Nomi (Ingliz)')),
                ('discreptin', models.TextField(verbose_name='Tavsif')),
                ('janr', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('series_count', models.IntegerField(default=0)),
                ('photo_id', models.TextField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number', models.IntegerField()),
                ('video_file_id', models.TextField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime')),
            ],
        ),
    ]
