# Generated by Django 6.0.1 on 2026-01-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_anime_subscriptions_video'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptions',
            unique_together={('anime', 'telegram_user_id')},
        ),
    ]
